# Now You Code In Class: Tricks of The Pandas Masters

We will try something a bit different in the Activity - A series of Pandas coding challenges!


For this Now You Code, you will need the Zomato api https://developers.zomato.com/api which provides API access to local area restaurants information.


In [54]:
import pandas as pd
import import_ipynb
import googleapi as google
import requests

pd.set_option('display.max_colwidth', None)
google_api_key = '751838d6b9978955679461c80a7df60bde4f093d'

## Warm-Up 1

Load the following data set into a data frame, called `exam_df`

https://raw.githubusercontent.com/mafudge/datasets/master/exam-scores/exam-scores.csv

HINT: observe the file format!

In [13]:
exam_df = pd.read_csv('https://raw.githubusercontent.com/mafudge/datasets/master/exam-scores/exam-scores.csv')
exam_df.sample(10) 

Class_Section Exam_Version  Completion_Time Made_Own_Study_Guide  \
57           M02            D               20                    Y   
23           M01            D               35                    ?   
12           M01            B               35                    Y   
34           M02            A               45                    Y   
20           M01            C               60                    ?   
36           M02            A               55                    Y   
8            M01            B               20                    N   
9            M01            B               20                    Y   
2            M01            A               30                    Y   
17           M01            C               45                    N   

   Did_Exam_Prep Assignment Studied_In_Groups  Student_Score Percentage  \
57                        Y                 N             21     70.00%   
23                        ?                 ?             13     43.30%   
12                        N                 Y             29     96.70%   
34                        Y                 N             24     80.00%   
20                        ?                 ?             22     73.30%   
36                        Y                 N             25     83.30%   
8                         N                 Y             13     43.30%   
9                         Y                 N             27     90.00%   
2                         Y                 Y             30    100.00%   
17                        Y                 Y             23     76.70%   

   Letter_Grade  
57           C+  
23            F  
12            A  
34            B  
20           C+  
36            B  
8             F  
9            A-  
2             A  
17           B-

## Warm-Up 2

Load the following HTML table into a data frame called `res_df`

https://en.wikipedia.org/wiki/Graphics_display_resolution#High-definition

HINT: Which table is it on the page?

In [20]:
vdf =  pd.read_html('https://en.wikipedia.org/wiki/Graphics_display_resolution#High-definition')
resolutions = vdf[5]
resolutions

Name  H (px)  V (px)   H:V  H × V (Mpx)
0      nHD     640     360  16:9        0.230
1      qHD     960     540  16:9        0.518
2       HD    1280     720  16:9        0.922
3      HD+    1600     900  16:9        1.440
4      FHD    1920    1080  16:9        2.074
5   (W)QHD    2560    1440  16:9        3.686
6     QHD+    3200    1800  16:9        5.760
7   4K UHD    3840    2160  16:9        8.294
8       5K    5120    2880  16:9       14.746
9   8K UHD    7680    4320  16:9       33.178
10     16K   15360    8640  16:9      132.710

## Warm-Up 3

For your `exam_df` display exams where the students made their own study guide  and finished in 30 minutes or less.

HINT: This can be multiple steps


In [36]:
madeown_df = exam_df[ exam_df['Made_Own_Study_Guide'] == 'Y']
made_fin_df = madeown_df [ madeown_df['Completion_Time'] < 30]

austin_df = made_fin_df['Exam_Version'] 
austin_df

mike_df = made_fin_df[   {'Exam_Version', "Letter_Grade"}   ]
mike_df

Exam_Version Letter_Grade
7             B           B+
9             B           A-
14            C           B+
48            C           A-
57            D           C+

In [37]:
made_fin_df.columns

Index(['Class_Section', 'Exam_Version', 'Completion_Time',
       'Made_Own_Study_Guide', 'Did_Exam_Prep Assignment', 'Studied_In_Groups',
       'Student_Score', 'Percentage', 'Letter_Grade'],
      dtype='object')

In [24]:
final_df = exam_df[  exam_df['Made_Own_Study_Guide'] == 'Y'][ exam_df['Completion_Time']< 30 ]
final_df

<ipython-input-24-857ee2aafb05>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  final_df = exam_df[  exam_df['Made_Own_Study_Guide'] == 'Y'][ exam_df['Completion_Time']< 30 ]


Class_Section Exam_Version  Completion_Time Made_Own_Study_Guide  \
7            M01            B               15                    Y   
9            M01            B               20                    Y   
14           M01            C               20                    Y   
48           M02            C               25                    Y   
57           M02            D               20                    Y   

   Did_Exam_Prep Assignment Studied_In_Groups  Student_Score Percentage  \
7                         Y                 Y             26     86.70%   
9                         Y                 N             27     90.00%   
14                        Y                 Y             26     86.70%   
48                        Y                 Y             28     93.30%   
57                        Y                 N             21     70.00%   

   Letter_Grade  
7            B+  
9            A-  
14           B+  
48           A-  
57           C+

## Warm-Up 4

For your `res_df`, display the displays which are larger than 1920 x 1080. Show columns `Name` and `H:V` only

HINT: Again, think multiple steps

In [40]:
res_h = resolutions [ resolutions['H (px)'] >1920]
res_hv = res_h [ res_h['V (px)'] >1080]
res_hv

Name  H (px)  V (px)   H:V  H × V (Mpx)
5   (W)QHD    2560    1440  16:9        3.686
6     QHD+    3200    1800  16:9        5.760
7   4K UHD    3840    2160  16:9        8.294
8       5K    5120    2880  16:9       14.746
9   8K UHD    7680    4320  16:9       33.178
10     16K   15360    8640  16:9      132.710

In [42]:
resolutions[5:]

Name  H (px)  V (px)   H:V  H × V (Mpx)
5   (W)QHD    2560    1440  16:9        3.686
6     QHD+    3200    1800  16:9        5.760
7   4K UHD    3840    2160  16:9        8.294
8       5K    5120    2880  16:9       14.746
9   8K UHD    7680    4320  16:9       33.178
10     16K   15360    8640  16:9      132.710

In [50]:
resolutions[ (resolutions['H (px)'] > 1920) & (resolutions['V (px)'] > 1080) ]

Name  H (px)  V (px)   H:V  H × V (Mpx)
5   (W)QHD    2560    1440  16:9        3.686
6     QHD+    3200    1800  16:9        5.760
7   4K UHD    3840    2160  16:9        8.294
8       5K    5120    2880  16:9       14.746
9   8K UHD    7680    4320  16:9       33.178
10     16K   15360    8640  16:9      132.710

## Challenge 1

1. Search the Open Street Maps  geocode api for "Syracuse" (leave off the NY) put the results in a dataframe (there should be several results). 

Example:
https://nominatim.openstreetmap.org/search?q=Syracuse&format=json



In [51]:
url = 'https://nominatim.openstreetmap.org/search?q=Syracuse&format=json'
response = requests.get(url)
response.raise_for_status()
locations = response.json()
locations


[{'place_id': 257841956,
  'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 174916,
  'boundingbox': ['42.9843709', '43.086102', '-76.2046029', '-76.074084'],
  'lat': '43.0481221',
  'lon': '-76.1474244',
  'display_name': 'Syracuse, Onondaga County, New York, United States',
  'class': 'boundary',
  'type': 'administrative',
  'importance': 0.6867762857760726,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png'},
 {'place_id': 257728182,
  'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 39169,
  'boundingbox': ['36.9477054', '37.1156703', '15.0829726', '15.3367251'],
  'lat': '37.0646139',
  'lon': '15.2907196',
  'display_name': 'Siracusa, Sicilia, Italia',
  'class': 'boundary',
  'type': 'administrative',
  'importance': 0.5980544326919952,
  'icon': 'https://nominatim.openstreetmap.org/ui

## Challenge 2

1. Load the locations into a dataframe. using the `pd.DataFrame()` method. Start with whatever is of type `list` as that will automatically place it into a `DataFrame` 


In [55]:
locations_df = pd.DataFrame(locations)
locations_df[ { 'display_name', 'lat', 'lon'}]

display_name  \
0                                          Syracuse, Onondaga County, New York, United States   
1                                                                   Siracusa, Sicilia, Italia   
2                                     Syracuse, Hamilton County, Kansas, 67878, United States   
3                                              Syracuse, Otoe County, Nebraska, United States   
4                                          Syracuse, Davis County, Utah, 84075, United States   
5  Syracuse, 131, NBT Bank Parkway, Syracuse, Onondaga County, New York, 13208, United States   
6                                            Syracuse, Morgan County, Missouri, United States   
7                                          Syracuse, Kosciusko County, Indiana, United States   
8                                          Syracuse, Meigs County, Ohio, 45779, United States   
9                                                                   Siracusa, Sicilia, Italia   

                  lon          lat  
0         -76.1474244   43.0481221  
1          15.2907196   37.0646139  
2        -101.7526719   37.9805686  
3          -96.186398    40.657224  
4        -112.0638903   41.0895938  
5         -76.1694003   43.0768312  
6         -92.8732509   38.6700209  
7         -85.7524957   41.4278409  
8         -81.9740274   38.9975789  
9  15.086780069913484  37.02983715

## Challenge 3

1. Let's call the IST256 google places search api, looking for bars in the Syracuse NY area, and load the results into a dataframe. You can call `google.googlePlacesSearch()` With these inputs lat=`43.0481`, lng=`-76.1474`, type=`'bar'`



In [60]:
places = google.googlePlacesSearch(google_api_key, '43.0481','-76.1474', 'bar')
places_df = pd.DataFrame(places)
places_df

business_status  \
0          OPERATIONAL   
1          OPERATIONAL   
2          OPERATIONAL   
3          OPERATIONAL   
4   CLOSED_TEMPORARILY   
5          OPERATIONAL   
6          OPERATIONAL   
7          OPERATIONAL   
8          OPERATIONAL   
9          OPERATIONAL   
10         OPERATIONAL   
11         OPERATIONAL   
12         OPERATIONAL   
13         OPERATIONAL   
14         OPERATIONAL   
15         OPERATIONAL   
16         OPERATIONAL   
17         OPERATIONAL   
18         OPERATIONAL   
19         OPERATIONAL   

                                                                                                                                                                                                                  geometry  \
0        {'location': {'lat': 43.0485021, 'lng': -76.15575319999999}, 'viewport': {'northeast': {'lat': 43.0499588802915, 'lng': -76.15439441970848}, 'southwest': {'lat': 43.04726091970851, 'lng': -76.15709238029149}}}   
1            {'location': {'lat': 43.04672, 'lng': -76.13756699999999}, 'viewport': {'northeast': {'lat': 43.0480367302915, 'lng': -76.1363070697085}, 'southwest': {'lat': 43.0453387697085, 'lng': -76.13900503029151}}}   
2         {'location': {'lat': 43.0478305, 'lng': -76.15470959999999}, 'viewport': {'northeast': {'lat': 43.04917948029149, 'lng': -76.15336061970848}, 'southwest': {'lat': 43.0464815197085, 'lng': -76.1560585802915}}}   
3       {'location': {'lat': 43.0418639, 'lng': -76.13684169999999}, 'viewport': {'northeast': {'lat': 43.04321178029149, 'lng': -76.13539986970851}, 'southwest': {'lat': 43.04051381970849, 'lng': -76.13809783029151}}}   
4         {'location': {'lat': 43.0481128, 'lng': -76.15388759999999}, 'viewport': {'northeast': {'lat': 43.04947563029149, 'lng': -76.15238011970848}, 'southwest': {'lat': 43.0467776697085, 'lng': -76.1550780802915}}}   
5                   {'location': {'lat': 43.05074, 'lng': -76.154507}, 'viewport': {'northeast': {'lat': 43.0520889802915, 'lng': -76.15315801970848}, 'southwest': {'lat': 43.0493910197085, 'lng': -76.15585598029149}}}   
6                    {'location': {'lat': 43.048176, 'lng': -76.153368}, 'viewport': {'northeast': {'lat': 43.0495457802915, 'lng': -76.1521210697085}, 'southwest': {'lat': 43.0468478197085, 'lng': -76.1548190302915}}}   
7                   {'location': {'lat': 43.052942, 'lng': -76.1537547}, 'viewport': {'northeast': {'lat': 43.0543317302915, 'lng': -76.1525218197085}, 'southwest': {'lat': 43.0516337697085, 'lng': -76.1552197802915}}}   
8            {'location': {'lat': 43.05237700000001, 'lng': -76.138954}, 'viewport': {'northeast': {'lat': 43.0536381302915, 'lng': -76.1376070197085}, 'southwest': {'lat': 43.0509401697085, 'lng': -76.1403049802915}}}   
9        {'location': {'lat': 43.0481533, 'lng': -76.15441729999999}, 'viewport': {'northeast': {'lat': 43.04940938029149, 'lng': -76.15308206970849}, 'southwest': {'lat': 43.04671141970849, 'lng': -76.1557800302915}}}   
10       {'location': {'lat': 43.05012019999999, 'lng': -76.1515045}, 'viewport': {'northeast': {'lat': 43.05157973029149, 'lng': -76.15007181970849}, 'southwest': {'lat': 43.0488817697085, 'lng': -76.15276978029151}}}   
11          {'location': {'lat': 43.04941199999999, 'lng': -76.1520069}, 'viewport': {'northeast': {'lat': 43.0507728802915, 'lng': -76.1507617197085}, 'southwest': {'lat': 43.0480749197085, 'lng': -76.1534596802915}}}   
12  {'location': {'lat': 43.05069699999999, 'lng': -76.15127199999999}, 'viewport': {'northeast': {'lat': 43.0521434302915, 'lng': -76.14991181970848}, 'southwest': {'lat': 43.0494454697085, 'lng': -76.1526097802915}}}   
13          {'location': {'lat': 43.0476609, 'lng': -76.14187679999999}, 'viewport': {'northeast': {'lat': 43.0490852802915, 'lng': -76.1406638197085}, 'southwest': {'lat': 43.0463873197085, 'lng': -76.1433617802915}}}   
14          {'location': {'lat': 43.048347, 'lng': -76.15326999999999}, 'viewport': {'northeast': {'lat': 43.0497036302915, 'lng':

## Challenge 4

Notice the nested JSON. Yuk. This can be fixed using `pd.json_normalize` instead of `pd.DataFrame`.

Fix the results above so that the nested JSON is flattened in the dataframe.


In [61]:
places_df = pd.json_normalize(places)
places_df

business_status  \
0          OPERATIONAL   
1          OPERATIONAL   
2          OPERATIONAL   
3          OPERATIONAL   
4   CLOSED_TEMPORARILY   
5          OPERATIONAL   
6          OPERATIONAL   
7          OPERATIONAL   
8          OPERATIONAL   
9          OPERATIONAL   
10         OPERATIONAL   
11         OPERATIONAL   
12         OPERATIONAL   
13         OPERATIONAL   
14         OPERATIONAL   
15         OPERATIONAL   
16         OPERATIONAL   
17         OPERATIONAL   
18         OPERATIONAL   
19         OPERATIONAL   

                                                                             icon  \
0          https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png   
1   https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png   
2          https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png   
3          https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png   
4          https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png   
5          https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png   
6          https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png   
7          https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png   
8          https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png   
9          https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png   
10         https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png   
11  https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png   
12         https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png   
13         https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png   
14  https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png   
15  https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png   
16  https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png   
17         https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png   
18  https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png   
19         https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png   

                                   name  \
0               Kitty Hoyne's Irish Pub   
1   Phoebe's Restaurant & Coffee Lounge   
2                             Blue Tusk   
3                   Faegan's Cafe & Pub   
4                 Syracuse Suds Factory   
5            Saltine Warrior Sports Pub   
6            Al's Wine & Whiskey Lounge   
7                                 Trexx   
8                  Guilfoil's Irish Pub   
9                         The Hops Spot   
10                             Maxwells   
11                    Anything But Beer   
12                        The Evergreen   
13                     Weighlock Lounge   
14                      Funk 'n Waffles   
15              Shaughnessy's Irish Pub   
16                             The York   
17                    Ale 'n' Angus Pub   
18                      Bistro Elephant   
19                   Clinton Street Pub   

                                                                                                                                                                                                                                                                                                                                                                                         photos  \
0                               [{'height': 3024, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/112556789907904985640">Jasmine Hindman</a>'], 'photo_reference': 'ATtYBwJdhyXmpgdUo6Y9GT2rBRm2IAXiL-E6D2yR6hDgw2itoqdrBh8JBcKnlmsJMjEqMQh8GyMCBRwO9gXy8Pm6egT6hE9laHmto2pCU0h6bbss-fGcN65pZEZw9y7PgeWgs2f4XFhl5dU5hrMZl6UP_JPktiXVfjKsf5xokEreo25LCftP', 'width': 4032}]

## Challenge 5

Convert your dataframe back into a list of dict.

1. use `to_records()` to convert the dataframe in Challenge 4 back into a `list` of `dict`.
2. loop over the rows and print the bar name, rating, and whether it is open now, 
   for only those rows where the bar is open now.

NOTE: The keys match he columns in the data frame.


In [64]:
places_df.columns
for row in places_df.to_records():
    print(row['name'], row['rating'], row['opening_hours.open_now'])

Kitty Hoyne's Irish Pub 4.6 True
Phoebe's Restaurant & Coffee Lounge 4.6 False
Blue Tusk 4.4 True
Faegan's Cafe & Pub 4.3 False
Syracuse Suds Factory 3.3 nan
Saltine Warrior Sports Pub 4.0 True
Al's Wine & Whiskey Lounge 4.6 True
Trexx 4.1 False
Guilfoil's Irish Pub 4.6 True
The Hops Spot 4.4 True
Maxwells 4.3 True
Anything But Beer 4.5 False
The Evergreen 4.5 True
Weighlock Lounge 4.8 False
Funk 'n Waffles 4.4 False
Shaughnessy's Irish Pub 4.1 True
The York 4.3 False
Ale 'n' Angus Pub 4.5 False
Bistro Elephant 4.4 nan
Clinton Street Pub 4.0 True


In [68]:
bars_in_cuse = places_df.to_records()
print(f'These bars are open:')
for bar in bars_in_cuse:
    if bar['opening_hours.open_now'] == True:
        print(f"- {bar['name']}")


These bars are open:
- Kitty Hoyne's Irish Pub
- Blue Tusk
- Saltine Warrior Sports Pub
- Al's Wine & Whiskey Lounge
- Guilfoil's Irish Pub
- The Hops Spot
- Maxwells
- The Evergreen
- Shaughnessy's Irish Pub
- Clinton Street Pub


In [ ]:
# run this code to turn in your work!
from coursetools.submission import Submission
Submission().submit_now()