# Now You Code In Class: Tricks of The Pandas Masters

We will try something a bit different in the Activity - A series of Pandas coding challenges!


For this Now You Code, you will need the Zomato api https://developers.zomato.com/api which provides API access to local area restaurants information.


In [1]:
import pandas as pd
import import_ipynb
import googleapi as google
import requests

google_api_key = '751838d6b9978955679461c80a7df60bde4f093d'

importing Jupyter notebook from googleapi.ipynb


## Warm-Up 1

Load the following data set into a data frame, called `exam_df`

https://raw.githubusercontent.com/mafudge/datasets/master/exam-scores/exam-scores.csv

HINT: observe the file format!

In [3]:
exam_df = pd.read_csv('https://raw.githubusercontent.com/mafudge/datasets/master/exam-scores/exam-scores.csv')
exam_df

Class_Section Exam_Version  Completion_Time Made_Own_Study_Guide  \
0            M01            A               20                    N   
1            M01            A               20                    ?   
2            M01            A               30                    Y   
3            M01            A               50                    N   
4            M01            A               55                    Y   
..           ...          ...              ...                  ...   
60           M02            D               40                    ?   
61           M02            D               45                    Y   
62           M02            D               45                    ?   
63           M02            D               55                    Y   
64           M02            D               60                    N   

   Did_Exam_Prep Assignment Studied_In_Groups  Student_Score Percentage  \
0                         N                 Y             24     80.00%   
1                         ?                 ?             27     90.00%   
2                         Y                 Y             30    100.00%   
3                         Y                 Y             18     60.00%   
4                         Y                 N             24     80.00%   
..                      ...               ...            ...        ...   
60                        ?                 ?             23     76.70%   
61                        Y                 N             22     73.30%   
62                        ?                 ?             24     80.00%   
63                        Y                 N             24     80.00%   
64                        N                 Y             24     80.00%   

   Letter_Grade  
0             B  
1            A-  
2             A  
3            C-  
4             B  
..          ...  
60           B-  
61           C+  
62            B  
63            B  
64            B  

[65 rows x 9 columns]

## Warm-Up 2

Load the following HTML table into a data frame called `res_df`

https://en.wikipedia.org/wiki/Graphics_display_resolution#High-definition

HINT: Which table is it on the page?

In [4]:
res_df = pd.read_html('https://en.wikipedia.org/wiki/Graphics_display_resolution#High-definition')
df1 = res_df[4]

df1

Height (px) Display aspect ratio[1]                                   \
   Height (px)              1.25 (5∶4)   1.3 (4∶3)            1.5 (3∶2)   
0          120                     NaN   160 QQVGA                  NaN   
1          144                     NaN         192                  NaN   
2          160                     NaN         NaN            240 HQVGA   
3          240                     NaN    320 QVGA            360 WQVGA   
4          320                     NaN         NaN             480 HVGA   
5          360                     NaN         480                  NaN   
6          480                     NaN     640 VGA             720 WVGA   
7          540                     NaN         NaN                  NaN   
8          576                     NaN     768 PAL                  NaN   
9          600                     750    800 SVGA                  NaN   
10         640                     NaN         NaN             960 DVGA   
11         720                     NaN         960                  NaN   
12         768                     960    1024 XGA            1152 WXGA   
13         800                     NaN         NaN                  NaN   
14         864                     NaN   1152 XGA+                 1280   
15         900                     NaN        1200                  NaN   
16         960                     NaN  1280 SXGA−          1440 FWXGA+   
17        1024               1280 SXGA         NaN           1600 WSXGA   
18        1050                     NaN  1400 SXGA+                  NaN   
19        1080                     NaN        1440                  NaN   
20        1152                     NaN         NaN                  NaN   
21        1200                    1500   1600 UXGA                  NaN   
22        1280                     NaN         NaN                 1920   
23        1440                     NaN        1920            2160 FHD+   
24        1536                     NaN   2048 QXGA                  NaN   
25        1600                     NaN         NaN                 2400   
26        1620                     NaN         NaN                  NaN   
27        1800                     NaN         NaN                  NaN   
28        1920                     NaN        2560                 2880   
29        2048              2560 QSXGA        2732  3200 WQSXGA (25∶16)   
30        2160                     NaN        2880                 3240   
31        2400                     NaN  3200 QUXGA                  NaN   
32        2560                     NaN         NaN                 3840   
33        2880                     NaN         NaN                  NaN   
34        3072                     NaN        4096                  NaN   
35        4320                     NaN         NaN                  NaN   

                                                                     \
            1.6 (16∶10)            1.6 (15∶9)            1.7 (16∶9)   
0                   NaN                   NaN                   NaN   
1                   NaN                   NaN                   256   
2                   NaN                   NaN                   NaN   
3             384 WQVGA             400 WQVGA      432 FWQVGA (9∶5)   
4                   NaN                   NaN                   NaN   
5                   NaN                   NaN               640 nHD   
6              768 WVGA              800 WVGA             854 FWVGA   
7                   NaN                   NaN               960 qHD   
8                   NaN                   NaN            1024 WSVGA   
9                   NaN  1024 WSVGA (≈ 17∶10)  1024 WSVGA (≈ 17∶10)   
10                 1024                   NaN                  1136   
11                 1152                   NaN        1280 HD / WXGA   
12                  NaN             1280 WXGA            1366 FWXGA   
13            1280 WXGA                   NaN                   NaN   
14              

## Warm-Up 3

For your `exam_df` display exams where the students made their own study guide  and finished in 30 minutes or less.

HINT: This can be multiple steps


In [5]:
sg = exam_df[ exam_df['Made_Own_Study_Guide'] == 'Y']
sg[sg['Completion_Time'] <= 30]

Class_Section Exam_Version  Completion_Time Made_Own_Study_Guide  \
2            M01            A               30                    Y   
7            M01            B               15                    Y   
9            M01            B               20                    Y   
14           M01            C               20                    Y   
48           M02            C               25                    Y   
57           M02            D               20                    Y   

   Did_Exam_Prep Assignment Studied_In_Groups  Student_Score Percentage  \
2                         Y                 Y             30    100.00%   
7                         Y                 Y             26     86.70%   
9                         Y                 N             27     90.00%   
14                        Y                 Y             26     86.70%   
48                        Y                 Y             28     93.30%   
57                        Y                 N             21     70.00%   

   Letter_Grade  
2             A  
7            B+  
9            A-  
14           B+  
48           A-  
57           C+

## Warm-Up 4

For your `res_df`, display the displays which are larger than 1920 x 1080. Show columns `Name` and `H:V` only

HINT: Again, think multiple steps

In [6]:
df1[df1[('Height (px)','Height (px)')] >=1080 ]

Height (px) Display aspect ratio[1]                                   \
   Height (px)              1.25 (5∶4)   1.3 (4∶3)            1.5 (3∶2)   
19        1080                     NaN        1440                  NaN   
20        1152                     NaN         NaN                  NaN   
21        1200                    1500   1600 UXGA                  NaN   
22        1280                     NaN         NaN                 1920   
23        1440                     NaN        1920            2160 FHD+   
24        1536                     NaN   2048 QXGA                  NaN   
25        1600                     NaN         NaN                 2400   
26        1620                     NaN         NaN                  NaN   
27        1800                     NaN         NaN                  NaN   
28        1920                     NaN        2560                 2880   
29        2048              2560 QSXGA        2732  3200 WQSXGA (25∶16)   
30        2160                     NaN        2880                 3240   
31        2400                     NaN  3200 QUXGA                  NaN   
32        2560                     NaN         NaN                 3840   
33        2880                     NaN         NaN                  NaN   
34        3072                     NaN        4096                  NaN   
35        4320                     NaN         NaN                  NaN   

                                                   \
            1.6 (16∶10) 1.6 (15∶9)     1.7 (16∶9)   
19                  NaN        NaN  1920 FHD / 2K   
20                  NaN        NaN     2048 QWXGA   
21           1920 WUXGA        NaN            NaN   
22                 2048        NaN            NaN   
23                 2304        NaN    2560 (W)QHD   
24                  NaN        NaN            NaN   
25           2560 WQXGA        NaN            NaN   
26                  NaN        NaN        2880 3K   
27                 2880        NaN      3200 QHD+   
28                 3072        NaN            NaN   
29  3200 WQSXGA (25∶16)        NaN            NaN   
30                  NaN        NaN    3840 4K UHD   
31          3840 WQUXGA        NaN            NaN   
32                 4096        NaN            NaN   
33                  NaN        NaN        5120 5K   
34                  NaN        NaN            NaN   
35                  NaN        NaN    7680 8K UHD   

                                                       \
                                           2.0 (18∶9)   
19                                  2160, 2280 (19∶9)   
20                                                NaN   
21                                                NaN   
22                                                NaN   
23  2880, 2960 (18.mw-parser-output .sfrac{white-s...   
24                                                NaN   
25                                                NaN   
26                                                NaN   
27                                                NaN   
28                                                NaN   
29                                                NaN   
30                                               4320   
31                                                NaN   
32                                                NaN   
33                                               5760   
34                                                NaN   
35                                                NaN   

                                                 
                           2.370 (64∶27 ≈ 21∶9)  
19                                         2560  
20                                          NaN  
21                                          NaN  
22                                          NaN  
23  3120 (191/2∶9), 3200 (20∶9), 3440 (211/2∶9)  
24                                          NaN  
25                                  3840 (12∶5)  
26                                 

## Challenge 1

1. Search the Open Street Maps  geocode api for "Syracuse" (leave off the NY) put the results in a dataframe (there should be several results). 

Example:
https://nominatim.openstreetmap.org/search?q=Syracuse&format=json



In [8]:
response = requests.get("https://nominatim.openstreetmap.org/search?q=Syracuse&format=json")
response.raise_for_status()
data = response.json()

[{'place_id': 257841956,
  'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 174916,
  'boundingbox': ['42.9843709', '43.086102', '-76.2046029', '-76.074084'],
  'lat': '43.0481221',
  'lon': '-76.1474244',
  'display_name': 'Syracuse, Onondaga County, New York, United States',
  'class': 'boundary',
  'type': 'administrative',
  'importance': 0.6867762857760726,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png'},
 {'place_id': 257728182,
  'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 39169,
  'boundingbox': ['36.9477054', '37.1156703', '15.0829726', '15.3367251'],
  'lat': '37.0646139',
  'lon': '15.2907196',
  'display_name': 'Siracusa, Sicilia, Italia',
  'class': 'boundary',
  'type': 'administrative',
  'importance': 0.5980544326919952,
  'icon': 'https://nominatim.openstreetmap.org/ui

## Challenge 2

1. Load the places into a dataframe. using the `pd.DataFrame()` method. Start with whatever is of type `list` as that will automatically place it into a `DataFrame` 


In [10]:
pdf = pd.DataFrame(data)
pdf

place_id                                            licence  osm_type  \
0  257841956  Data © OpenStreetMap contributors, ODbL 1.0. h...  relation   
1  257728182  Data © OpenStreetMap contributors, ODbL 1.0. h...  relation   
2  257785961  Data © OpenStreetMap contributors, ODbL 1.0. h...  relation   
3  257190791  Data © OpenStreetMap contributors, ODbL 1.0. h...  relation   
4  258183983  Data © OpenStreetMap contributors, ODbL 1.0. h...  relation   
5   69010415  Data © OpenStreetMap contributors, ODbL 1.0. h...      node   
6  257152602  Data © OpenStreetMap contributors, ODbL 1.0. h...  relation   
7  257782630  Data © OpenStreetMap contributors, ODbL 1.0. h...  relation   
8  258361658  Data © OpenStreetMap contributors, ODbL 1.0. h...  relation   
9  257738503  Data © OpenStreetMap contributors, ODbL 1.0. h...  relation   

       osm_id                                        boundingbox          lat  \
0      174916   [42.9843709, 43.086102, -76.2046029, -76.074084]   43.0481221   
1       39169   [36.9477054, 37.1156703, 15.0829726, 15.3367251]   37.0646139   
2      129906   [37.941272, 37.990492, -101.816776, -101.736708]   37.9805686   
3      169314     [40.651206, 40.672865, -96.197821, -96.172004]    40.657224   
4      198737  [41.0529648, 41.11093, -112.1159667, -112.035662]   41.0895938   
5  6241108067  [43.0718312, 43.0818312, -76.1744003, -76.1644...   43.0768312   
6      141314      [38.665793, 38.67337, -92.883419, -92.869404]   38.6700209   
7      127610      [41.403028, 41.43607, -85.768612, -85.734116]   41.4278409   
8      182667   [38.9922728, 39.007177, -81.9841277, -81.943146]   38.9975789   
9       39155   [36.6441671, 37.4128826, 14.7729261, 15.3367251]  37.02983715   

                  lon                                       display_name  \
0         -76.1474244  Syracuse, Onondaga County, New York, United St...   
1          15.2907196                          Siracusa, Sicilia, Italia   
2        -101.7526719  Syracuse, Hamilton County, Kansas, 67878, Unit...   
3          -96.186398     Syracuse, Otoe County, Nebraska, United States   
4        -112.0638903  Syracuse, Davis County, Utah, 84075, United St...   
5         -76.1694003  Syracuse, 131, NBT Bank Parkway, Syracuse, Ono...   
6         -92.8732509   Syracuse, Morgan County, Missouri, United States   
7         -85.7524957  Syracuse, Kosciusko County, Indiana, United St...   
8         -81.9740274  Syracuse, Meigs County, Ohio, 45779, United St...   
9  15.086780069913484                          Siracusa, Sicilia, Italia   

      class            type  importance  \
0  boundary  administrative    0.686776   
1  boundary  administrative    0.598054   
2  boundary  administrative    0.535495   
3  boundary  administrative    0.461126   
4  boundary  administrative    0.436855   
5   railway         station    0.427252   
6  boundary  administrative    0.420439   
7  boundary  administrative    0.420439   
8  boundary  administrative    0.409042   
9  boundary  administrative    0.404285   

                                                icon  
0  https://nominatim.openstreetmap.org/ui/mapicon...  
1  https://nominatim.openstreetmap.org/ui/mapicon...  
2  https://nominatim.openstreetmap.org/ui/mapicon...  
3  https://nominatim.openstreetmap.org/ui/mapicon...  
4  https://nominatim.openstreetmap.org/ui/mapicon...  
5  https://nominatim.openstreetmap.org/ui/mapicon...  
6  https://nominatim.openstreetmap.org/ui/mapicon...  
7  https://nominatim.openstreetmap.org/ui/mapicon...  
8  https://nominatim.openstreetmap.org/ui/mapicon...  
9  https://nominatim.openstreetmap.org/ui/mapicon...

## Challenge 3

1. Let's call the IST256 google places search api, looking for bars in the Syracuse NY area, and load the results into a dataframe. You can call `google.googlePlacesSearch()` With these inputs lat=`43.0481`, lng=`-76.1474`, type=`'bar'`



In [18]:
data = google.googlePlacesSearch(lat=43.0481, lng=-76.1474,place_type='bar',google_api_key=google_api_key)

gdf = pd.DataFrame(data)
gdf

business_status                                           geometry  \
0          OPERATIONAL  {'location': {'lat': 43.0485021, 'lng': -76.15...   
1          OPERATIONAL  {'location': {'lat': 43.04672, 'lng': -76.1375...   
2          OPERATIONAL  {'location': {'lat': 43.0478305, 'lng': -76.15...   
3          OPERATIONAL  {'location': {'lat': 43.0418639, 'lng': -76.13...   
4   CLOSED_TEMPORARILY  {'location': {'lat': 43.0481128, 'lng': -76.15...   
5          OPERATIONAL  {'location': {'lat': 43.05074, 'lng': -76.1545...   
6          OPERATIONAL  {'location': {'lat': 43.048176, 'lng': -76.153...   
7          OPERATIONAL  {'location': {'lat': 43.052942, 'lng': -76.153...   
8          OPERATIONAL  {'location': {'lat': 43.05237700000001, 'lng':...   
9          OPERATIONAL  {'location': {'lat': 43.0481533, 'lng': -76.15...   
10         OPERATIONAL  {'location': {'lat': 43.05012019999999, 'lng':...   
11         OPERATIONAL  {'location': {'lat': 43.04941199999999, 'lng':...   
12         OPERATIONAL  {'location': {'lat': 43.05069699999999, 'lng':...   
13         OPERATIONAL  {'location': {'lat': 43.0476609, 'lng': -76.14...   
14         OPERATIONAL  {'location': {'lat': 43.048347, 'lng': -76.153...   
15         OPERATIONAL  {'location': {'lat': 43.0444715, 'lng': -76.15...   
16         OPERATIONAL  {'location': {'lat': 43.0485311, 'lng': -76.15...   
17         OPERATIONAL  {'location': {'lat': 43.0442185, 'lng': -76.14...   
18         OPERATIONAL  {'location': {'lat': 43.04758830000001, 'lng':...   
19         OPERATIONAL  {'location': {'lat': 43.04852869999999, 'lng':...   

                                                 icon  \
0   https://maps.gstatic.com/mapfiles/place_api/ic...   
1   https://maps.gstatic.com/mapfiles/place_api/ic...   
2   https://maps.gstatic.com/mapfiles/place_api/ic...   
3   https://maps.gstatic.com/mapfiles/place_api/ic...   
4   https://maps.gstatic.com/mapfiles/place_api/ic...   
5   https://maps.gstatic.com/mapfiles/place_api/ic...   
6   https://maps.gstatic.com/mapfiles/place_api/ic...   
7   https://maps.gstatic.com/mapfiles/place_api/ic...   
8   https://maps.gstatic.com/mapfiles/place_api/ic...   
9   https://maps.gstatic.com/mapfiles/place_api/ic...   
10  https://maps.gstatic.com/mapfiles/place_api/ic...   
11  https://maps.gstatic.com/mapfiles/place_api/ic...   
12  https://maps.gstatic.com/mapfiles/place_api/ic...   
13  https://maps.gstatic.com/mapfiles/place_api/ic...   
14  https://maps.gstatic.com/mapfiles/place_api/ic...   
15  https://maps.gstatic.com/mapfiles/place_api/ic...   
16  https://maps.gstatic.com/mapfiles/place_api/ic...   
17  https://maps.gstatic.com/mapfiles/place_api/ic...   
18  https://maps.gstatic.com/mapfiles/place_api/ic...   
19  https://maps.gstatic.com/mapfiles/place_api/ic...   

                                   name        opening_hours  \
0               Kitty Hoyne's Irish Pub   {'open_now': True}   
1   Phoebe's Restaurant & Coffee Lounge  {'open_now': False}   
2                             Blue Tusk   {'open_now': True}   
3                   Faegan's Cafe & Pub  {'open_now': False}   
4                 Syracuse Suds Factory                  NaN   
5            Saltine Warrior Sports Pub   {'open_now': True}   
6            Al's Wine & Whiskey Lounge  {'open_now': False}   
7                                 Trexx  {'open_now': False}   
8                  Guilfoil's Irish Pub   {'open_now': True}   
9                         The Hops Spot  {'open_now': False}   
10                             Maxwells  {'open_now': False}   
11                    Anything But Beer  {'open_now': False}   
12                        The Evergreen  {'open_now': False}   
13                     Weighlock Lounge  {'open_now': False}   
14                      Funk 'n Waffles   {'open_now': True}   
15              Shaughnessy's Irish Pub  {'open_now': False}   
16                             The York  {'open_now': False}   
17                    Ale 'n' Angus Pub

## Challenge 4

Notice the nested JSON. Yuk. This can be fixed using `pd.json_normalize` instead of `pd.DataFrame`.

Fix the results above so that the nested JSON is flattened in the dataframe.


In [20]:
flat_gdf = pd.json_normalize(data)
flat_gdf

business_status                                               icon  \
0          OPERATIONAL  https://maps.gstatic.com/mapfiles/place_api/ic...   
1          OPERATIONAL  https://maps.gstatic.com/mapfiles/place_api/ic...   
2          OPERATIONAL  https://maps.gstatic.com/mapfiles/place_api/ic...   
3          OPERATIONAL  https://maps.gstatic.com/mapfiles/place_api/ic...   
4   CLOSED_TEMPORARILY  https://maps.gstatic.com/mapfiles/place_api/ic...   
5          OPERATIONAL  https://maps.gstatic.com/mapfiles/place_api/ic...   
6          OPERATIONAL  https://maps.gstatic.com/mapfiles/place_api/ic...   
7          OPERATIONAL  https://maps.gstatic.com/mapfiles/place_api/ic...   
8          OPERATIONAL  https://maps.gstatic.com/mapfiles/place_api/ic...   
9          OPERATIONAL  https://maps.gstatic.com/mapfiles/place_api/ic...   
10         OPERATIONAL  https://maps.gstatic.com/mapfiles/place_api/ic...   
11         OPERATIONAL  https://maps.gstatic.com/mapfiles/place_api/ic...   
12         OPERATIONAL  https://maps.gstatic.com/mapfiles/place_api/ic...   
13         OPERATIONAL  https://maps.gstatic.com/mapfiles/place_api/ic...   
14         OPERATIONAL  https://maps.gstatic.com/mapfiles/place_api/ic...   
15         OPERATIONAL  https://maps.gstatic.com/mapfiles/place_api/ic...   
16         OPERATIONAL  https://maps.gstatic.com/mapfiles/place_api/ic...   
17         OPERATIONAL  https://maps.gstatic.com/mapfiles/place_api/ic...   
18         OPERATIONAL  https://maps.gstatic.com/mapfiles/place_api/ic...   
19         OPERATIONAL  https://maps.gstatic.com/mapfiles/place_api/ic...   

                                   name  \
0               Kitty Hoyne's Irish Pub   
1   Phoebe's Restaurant & Coffee Lounge   
2                             Blue Tusk   
3                   Faegan's Cafe & Pub   
4                 Syracuse Suds Factory   
5            Saltine Warrior Sports Pub   
6            Al's Wine & Whiskey Lounge   
7                                 Trexx   
8                  Guilfoil's Irish Pub   
9                         The Hops Spot   
10                             Maxwells   
11                    Anything But Beer   
12                        The Evergreen   
13                     Weighlock Lounge   
14                      Funk 'n Waffles   
15              Shaughnessy's Irish Pub   
16                             The York   
17                    Ale 'n' Angus Pub   
18                      Bistro Elephant   
19                   Clinton Street Pub   

                                               photos  \
0   [{'height': 3024, 'html_attributions': ['<a hr...   
1   [{'height': 4032, 'html_attributions': ['<a hr...   
2   [{'height': 1366, 'html_attributions': ['<a hr...   
3   [{'height': 1210, 'html_attributions': ['<a hr...   
4   [{'height': 2666, 'html_attributions': ['<a hr...   
5   [{'height': 1000, 'html_attributions': ['<a hr...   
6   [{'height': 3024, 'html_attributions': ['<a hr...   
7   [{'height': 3024, 'html_attributions': ['<a hr...   
8   [{'height': 452, 'html_attributions': ['<a hre...   
9   [{'height': 3024, 'html_attributions': ['<a hr...   
10  [{'height': 1960, 'html_attributions': ['<a hr...   
11  [{'height': 922, 'html_attributions': ['<a hre...   
12  [{'height': 1169, 'html_attributions': ['<a hr...   
13  [{'height': 1920, 'html_attributions': ['<a hr...   
14  [{'height': 381, 'html_attributions': ['<a hre...   
15  [{'height': 4016, 'html_attributions': ['<a hr...   
16  [{'height': 3024, 'html_attributions': ['<a hr...   
17  [{'height': 4032, 'html_attributions': ['<a hr...   
18  [{'height': 1365, 'html_attributions': ['<a hr...   
19  [{'height': 4032, 'html_attributions': ['<a hr...   

                       place_id  price_level  rating  \
0   ChIJ2abhW8fz2YkRq_i-OkgGh7c          2.0     4.6   
1   ChIJ4XPPn6bz2YkRKrZtWuXTaA0          2.0     4.6   
2   ChIJYcGiq7jz2YkR2Ah1e3mkNOg          2.0     4.4   
3   ChIJn5r_W5_z2YkR67VB2u5qyRw          2.0     4.3   
4   ChI

## Challenge 5

Convert your dataframe back into a list of dict.

1. use `to_records()` to convert the dataframe in Challenge 4 back into a `list` of `dict`.
2. loop over the rows and print the bar name, rating, and whether it is open now, 
   for only those rows where the bar is open now.

NOTE: The keys match the columns in the data frame.


In [21]:
for row in flat_gdf.to_records():
    print(row['name'], row['rating'], row['opening_hours.open_now'])

Kitty Hoyne's Irish Pub 4.6 True
Phoebe's Restaurant & Coffee Lounge 4.6 False
Blue Tusk 4.4 True
Faegan's Cafe & Pub 4.3 False
Syracuse Suds Factory 3.3 nan
Saltine Warrior Sports Pub 4.0 True
Al's Wine & Whiskey Lounge 4.6 False
Trexx 4.1 False
Guilfoil's Irish Pub 4.6 True
The Hops Spot 4.4 False
Maxwells 4.3 False
Anything But Beer 4.5 False
The Evergreen 4.5 False
Weighlock Lounge 4.8 False
Funk 'n Waffles 4.4 True
Shaughnessy's Irish Pub 4.1 False
The York 4.3 False
Ale 'n' Angus Pub 4.5 True
Bistro Elephant 4.4 nan
Clinton Street Pub 4.0 False


In [ ]:
# run this code to turn in your work!
from coursetools.submission import Submission
Submission().submit_now()